[general]
project_name = "code-story"
description = "A system to convert codebases into richly-linked knowledge graphs with natural-language summaries"
version = "0.1.0"

[services]
service_host = "0.0.0.0"
service_port = 8000
worker_concurrency = 4
log_level = "INFO"
enable_telemetry = true
environment = "development"

[neo4j]
uri = "bolt://neo4j:7687"
database = "neo4j"

[redis]
uri = "redis://redis:6379"

[openai]
model = "gpt-4o-2024-05-13"
temperature = 0.1
max_tokens = 4096

[azure_openai]
deployment_id = "gpt-4o"
api_version = "2024-05-01"

[ingestion]
chunk_size = 1024
chunk_overlap = 200
embedding_model = "text-embedding-3-large"
embedding_dimensions = 3072
retry_attempts = 3
retry_backoff = 2.0

[plugins]
enabled = ["blarify", "filesystem", "summarizer", "docgrapher"]
plugin_directory = "plugins"

[telemetry]
metrics_port = 9090
metrics_endpoint = "/metrics"
trace_sample_rate = 1.0
log_format = "json"