repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: mixed-line-ending
        args: ['--fix=lf']

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
    -   id: ruff
        args: ["--fix"]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            'pydantic>=2.7.0',
            'types-redis>=5.0.0',
            'types-requests>=2.0.0',
        ]
        exclude: ^(docs/|tests/)

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
    -   id: eslint
        files: \.(js|ts|jsx|tsx)$
        types: [file]
        args: ['--fix']
        additional_dependencies:
        -   eslint@8.57.0
        -   '@typescript-eslint/eslint-plugin@7.3.1'
        -   '@typescript-eslint/parser@7.3.1'
        -   eslint-plugin-react-hooks@4.6.0
        -   eslint-plugin-react-refresh@0.4.6
        -   typescript@5.4.5

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, yaml]