line-length = 100
target-version = "py312"

[lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "RUF", # ruff-specific rules
    "D",   # pydocstyle
]
ignore = [
    # Docstring-related rules we defer
    "D100", "D101", "D107",
    "D200", "D203", "D212",
    # Import / style length
    "E402", "E501",
    # Pyupgrade / naming / bugbear we relax
    "UP035", "UP006", "UP007", "UP015",
    "B007", "B015", "B008",
    "N806",
    # Simplify & Ruff-specific suggestions postponed
    "SIM102", "SIM105", "SIM115", "SIM117",
    "RUF012",
    # Misc
    "F401",
    "C420",
]

[lint.per-file-ignores]
"tests/**/*.py" = ["D", "S101"]
"**/__init__.py" = ["F401"]

[lint.isort]
known-first-party = ["codestory"]
known-third-party = ["fastapi", "pydantic", "celery", "neo4j", "openai"]

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"