services:
  service:
    volumes:
      - /var/folders/h5/cvgpmjrd26l2vbpk9cymp__40000gn/T/tmptoj0fipr:/repositories/tmptoj0fipr:ro
  worker:
    volumes:
      - /var/folders/h5/cvgpmjrd26l2vbpk9cymp__40000gn/T/tmptoj0fipr:/repositories/tmptoj0fipr:ro
