services:
  service:
    environment:
      - AZURE_TENANT_ID=3cd87a41-1f61-4aef-a212-cefdecd9a2d1
      - USE_REAL_ADAPTERS=true
    volumes:
      - /tmp/test-repo-small:/repositories/test-repo-small:ro
      - ~/.azure:/root/.azure
  worker:
    environment:
      - CELERY_TASK_ALWAYS_EAGER=true  # Run Celery tasks synchronously for easier testing
      - AZURE_TENANT_ID=3cd87a41-1f61-4aef-a212-cefdecd9a2d1
    volumes:
      - /tmp/test-repo-small:/repositories/test-repo-small:ro
      - ~/.azure:/root/.azure