services:
  service:
    environment:
      # Override environment variables for service to fix Azure authentication issues
      - CODESTORY_NO_MODEL_CHECK=true
      - OPENAI__API_KEY=sk-dummy-apikey
    volumes:
      - /Users/ryan/src/msec/code-story:/repositories/code-story:ro
      
  worker:
    environment:
      # Override environment variables for worker to fix Azure authentication issues  
      - CODESTORY_NO_MODEL_CHECK=true
      - OPENAI__API_KEY=sk-dummy-apikey
    volumes:
      - /Users/ryan/src/msec/code-story:/repositories/code-story:ro