services:
  service:
    volumes:
      - /var/folders/h5/cvgpmjrd26l2vbpk9cymp__40000gn/T/tmpaw_6iub0:/repositories/tmpaw_6iub0:ro
  worker:
    volumes:
      - /var/folders/h5/cvgpmjrd26l2vbpk9cymp__40000gn/T/tmpaw_6iub0:/repositories/tmpaw_6iub0:ro
