services:
  service:
    environment:
      - CODESTORY_NO_MODEL_CHECK=true
    volumes:
      - /tmp/test-repo-small:/repositories/test-repo-small:ro
  worker:
    environment:
      - CODESTORY_NO_MODEL_CHECK=true
      - CELERY_TASK_ALWAYS_EAGER=true  # Run Celery tasks synchronously for easier testing
    volumes:
      - /tmp/test-repo-small:/repositories/test-repo-small:ro
