version: '3.8'

services:
  neo4j:
    image: neo4j:5.18.0
    container_name: codestory-neo4j-test
    ports:
      - "7475:7474"  # HTTP - using different port to avoid conflicts
      - "7688:7687"  # Bolt - using different port to avoid conflicts
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=512m
      # Neo4j 5.x uses a different configuration format for databases
      - NEO4J_initial_dbms_default__database=codestory-test
    # Using volumes with simpler names
    volumes:
      - neo4j_test_data:/data
      - neo4j_test_logs:/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.4-alpine
    container_name: codestory-redis-test
    ports:
      - "6380:6379"  # Using different port to avoid conflicts
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  neo4j_test_data:
  neo4j_test_logs:
  redis_test_data: