[tool.poetry]
name = "code-story"
version = "0.1.0"
description = "Service to ingest a code repo, build a Neo4j knowledge graph, and expose it via MCP, CLI, and GUI."
authors = ["Rysweet <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
ruff = "^0.0.241"
mypy = "^1.5.1"
pytest = "^7.3.1"

[tool.poetry.scripts]
code-story = "code_story.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
