global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
        labels:
          instance: 'neo4j_instance'

  - job_name: 'codestory'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          instance: 'codestory_instance'